### ISSUE TITLE
Canadian Museum for Human Rights

### ISSUE THREAD

**Issue by janetpkr** [creativecommons/Single-provider-website-adoptions#1]
Initial conversation with https://humanrights.ca/ for CC adoption

**Comment by cablegreen** [comment]
talking with:
John Young
Interim Provost UNBC

**Comment by janetpkr** [comment]
@cablegreen How did this go? Are they adopting CC?

**Comment by cablegreen** [comment]
Had a good call. He is talking with the Board - will work to get CC on a next Board agenda. Waiting for John Young to get back to me.
